-- ═══════════════════════════════════════════════════════════════════════════
-- BILINGUAL CONTENT SCHEMA — FA/EN i18n for app_content + membership_rules
-- ═══════════════════════════════════════════════════════════════════════════
-- Adds English columns to two tables that currently store Persian-only content:
--
--   1. app_content       — About / Terms / Privacy (CMS)
--   2. membership_rules  — Premium membership rules (versioned)
--
-- SAFETY (per spec):
--   • 100% idempotent (IF NOT EXISTS, UPDATE ... WHERE _en IS NULL)
--   • No DROP, no TRUNCATE, no DELETE of existing data
--   • Existing Persian columns (title, sections, body_markdown, summary) UNTOUCHED
--   • Re-running is safe: backfill only fills NULL English columns
--     (admin edits to English content are preserved on re-run)
--
-- Run against: Supabase PostgreSQL (DATABASE_URL)
-- ═══════════════════════════════════════════════════════════════════════════

-- ─── 1. app_content: add English columns ───────────────────────────────────
ALTER TABLE app_content ADD COLUMN IF NOT EXISTS title_en TEXT;
ALTER TABLE app_content ADD COLUMN IF NOT EXISTS sections_en JSONB NOT NULL DEFAULT '[]'::jsonb;

-- ─── 1b. app_content: backfill English content for existing rows ───────────
-- Only fills rows where title_en IS NULL (preserves admin edits on re-run).
-- Persian content (title, sections) is NEVER modified.

UPDATE app_content SET title_en = 'About Us',
  sections_en = '[
    {"heading":"AmirBTC Assistant","body":"AmirBTC Assistant is an intelligent financial markets assistant designed to provide fast information, smart analysis, and practical tools for market participants.\n\nThis platform aims to deliver market data, important news, smart analysis, and the tools financial market participants need in a fast, simple, and professional environment."},
    {"heading":"Features","body":"• Smart analysis of market news\n• Assessing the impact of news on the market\n• Quick access to important market information\n• Market management and tracking tools\n• Fast and modern user experience"},
    {"heading":"Mission","body":"Our goal is to build a professional tool that helps users make more informed decisions in the fast and complex environment of financial markets."}
  ]'::jsonb
WHERE id = 'about' AND title_en IS NULL;

UPDATE app_content SET title_en = 'Terms & Conditions',
  sections_en = '[
    {"heading":"1. Information Provided","body":"The information provided in the app is for informational and educational purposes only and should not be considered as financial advice, investment recommendation, or profit guarantee."},
    {"heading":"2. Market Risk","body":"Financial markets carry high risk, and users are responsible for their own trading decisions."},
    {"heading":"3. Analysis Accuracy","body":"Analyses and information generated by AI may contain errors, and users should conduct independent research before making any decisions."},
    {"heading":"4. Legal Use","body":"Use of the app services must comply with applicable laws and regulations."},
    {"heading":"5. Prohibition of Abuse","body":"Any abuse, attempt to disrupt the service, or unauthorized use of the app features is prohibited."},
    {"heading":"6. Liability","body":"The AmirBTC team strives to provide accurate and up-to-date information but is not responsible for market changes or the results of user decisions."}
  ]'::jsonb
WHERE id = 'terms' AND title_en IS NULL;

UPDATE app_content SET title_en = 'Privacy Policy',
  sections_en = '[
    {"heading":"1. Account Information","body":"Information required to provide services and personalize the user experience is used."},
    {"heading":"2. Usage Information","body":"Data related to app usage may be reviewed to improve performance and resolve technical issues."},
    {"heading":"3. Personal Information","body":"User information is not sold or provided to third parties without their consent."},
    {"heading":"4. Security","body":"We strive to protect user information using appropriate security methods."},
    {"heading":"5. External Services","body":"Some services such as market data APIs or AI services may be used to provide app features."},
    {"heading":"6. Changes","body":"This policy may change in the future to improve services, and the new version will be displayed in the app."}
  ]'::jsonb
WHERE id = 'privacy' AND title_en IS NULL;

-- ─── 2. membership_rules: add English columns ─────────────────────────────
ALTER TABLE membership_rules ADD COLUMN IF NOT EXISTS title_en TEXT;
ALTER TABLE membership_rules ADD COLUMN IF NOT EXISTS body_markdown_en TEXT;
ALTER TABLE membership_rules ADD COLUMN IF NOT EXISTS summary_en TEXT;

-- ─── 2b. membership_rules: backfill English content for existing rows ──────
-- Only fills rows where title_en IS NULL (preserves admin edits on re-run).
-- Persian columns (title, body_markdown, summary) UNTOUCHED.

UPDATE membership_rules SET
  title_en = 'Premium Membership Rules — Version 1',
  body_markdown_en = E'# Premium Membership Rules\n\n## What is Premium?\n\nPremium membership is a special access tier that provides additional benefits in exchange for meeting membership conditions. Premium is not a paid subscription; it is a reward for users who are active in the AMIRBTC ecosystem and meet the membership conditions.\n\n## Premium Benefits\n\n- Higher quota for price alerts, AI chat, and other high-usage features\n- Access to the Premium Rewards Store (purchase with AB Token)\n- Access to the Profile Cosmetics Store (profile customization with AB Token)\n- Premium badge on profile\n- Priority access to new features and exclusive campaigns\n\n**Note:** Premium does not mean unlimited. For resource-intensive features, the Premium quota is higher than regular users but still limited.\n\n## Conditions for Maintaining Premium\n\n1. The user account must be active and accessible.\n2. Membership in the official AMIRBTC channel must be maintained.\n3. The current Exchange Requirement must be met.\n\n## Exchange Requirement\n\nAt any time, one exchange is defined as the "required exchange." The required exchange may change in the future. If it changes, a grace period is provided for you to comply.\n\n## Changes to Rules\n\nThese rules may be updated in the future. New users must accept the new version. Existing Premium users do not need to re-accept unless the changes are fundamental.\n\n## Acceptance of Rules\n\nBy accepting these rules, you confirm that you have read and accepted the rules and understand that Premium is a benefit conditional on meeting the requirements, not an absolute right.',
  summary_en = 'Complete Premium Membership Rules — conditions, benefits, limitations, and acceptance'
WHERE title_en IS NULL;

-- ═══════════════════════════════════════════════════════════════════════════
-- END — bilingual-content-schema.sql
-- Re-runnable: safe to execute multiple times.
-- ═══════════════════════════════════════════════════════════════════════════
